### PR TITLE
use cached token if secret has not changed

### PR DESCRIPTION
**Pull request by krishnasrinivas**
req.csrfToken() was generating new token every time instead of reusing already generated token.

### CODE REVIEW

**Comment by dougwilson** [comment]
The description in the PR and what was actually changed are completely different. I'm not sure what you are trying to fix, I'm sorry.

req.csrfToken() MUST return a new token for every request--it is part of the security requirements of CSRF.

**Comment by krishnasrinivas** [comment]
@dougwilson in index.js check for the comment "// use cached token if secret has not changed" - line 72. Generating new token if you already have a token doesn't make sense. You should generate a new token only if the secret has changed. If an attacker has access to a token he can just use it as the secret would not have changed and hence verifytoken() [line:72] will pass. Re-generating the token will not help.

**Comment by dougwilson** [comment]
Can you tell me what you are trying to accomplish? Is getting a new token per request not working for you? Does generating take a significant amount ofwall clock time?

**Comment by krishnasrinivas** [comment]
I was reviewing the code to see why the token was changing and how it helped - could not find a good answer. So raised this issue to check how it will help. I am not facing any issues with cpu usage.

**Comment by dougwilson** [comment]
Gotcha. I'll reopen, but I can say that it was intentionally designed to be different per request.

**Comment by dougwilson** [comment]
If it wasn't support to be different per request, we would only need to store the token in the session, rather than the generated secret.

The change in this PR will still generate a new token for every request that is not a form submission, though, so I'm not sure what it really accomplishes in regards to not generating new tokens.

**Comment by krishnasrinivas** [comment]
According to [this](http://stackoverflow.com/questions/8655817/csrf-protection-do-we-have-to-generate-a-token-for-every-form) and [this](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#General_Recommendation%3a_Synchronizer_Token_Pattern), in general you can generate one token and store it in the session.

Wonder how RoR and Django implement this?

**Comment by jonathanong** [comment]
don't really see this point of this. creating more than 1 token per request uses very little CPU. you can always cache it yourself. no need to memoize stuff unless it's a performance issue or a lazy getter.

what's stored in the session is the "secret". what get's passed as the "CSRF token" is the token. in older frameworks before the BREACH attack was made public, these are the same. See "CSRF Token Defence" in https://community.qualys.com/blogs/securitylabs/2013/08/07/defending-against-the-breach-attack.

**Comment by jonathanong** [comment]
@krishnasrinivas if you have more questions about CSRF, please open up an issue here: https://github.com/pillarjs/understanding-csrf :)

**Comment by krishnasrinivas** [comment]
@jonathanong thanks for the explanation! will go through the breach attack link.

**Pull request closed without merging**
