### PR TITLE
added example of csurf ignoring routers

### PR DESCRIPTION
**Pull request by gabeio**
added an example of how to ignore routes/routers using csurf globally

### CODE REVIEW

**Comment by gabeio** [comment]
@dougwilson added for #75 as requested.

**Comment by alexbooker** [comment]
It may be worthwhile linking #75 (in the readme).

**Comment by dougwilson** [comment]
huh, since this wasn't assigned to me, I forgot it existed. Weird that the diff is blank?

**Comment by gabeio** [comment]
>.> cries i think I deleted the branch by accident while i was syncing csurf...

**Comment by gabeio** [comment]
this is why I need to always make a different branch -.-

**Pull request closed without merging**
